
#ifndef VEGETATION_DEFINES
#define VEGETATION_DEFINES

#define BUFFER_SIZE_RAM_VRAM 100
#define MAX_LOD_LEVELS 5
#define MAX_MODELS_ALLOWED 10

#define BIG_TREE 0,
#define MEDIUM_TREE 1,
#define BIG_BUSH 2,
#define MEDIUM_BUSH 3,
#define GROUND_VEGETATION 4,
#define DENSE_GROUND_VEGETATION  5

#define NO_VEGETATION_COVER -1
#define INVALID_LAYER -1
#define INVALID_POSITION float2(INFINITY, INFINITY)
#define MAX_LAYER_COUNTER 16
#define EPSLON 0.0001

#define GROUND_INDEX 0
#define FOREST_INDEX 1
#define MOISTURE_INDEX 2
#define PRECIPITATION_INDEX 3
#define HEIGHT_INDEX 4
#define SLOPE_INDEX 5

#define FEATURES_COUNT 6

#endif